name = "ritzy"
license = "MIT"
licenselink = "https://github.com/ddritzenhoff/ritzy/blob/main/LICENSE"
description = "A clean, minimal portfolio theme for writers, developers, and creatives"
homepage = "https://github.com/ddritzenhoff/ritzy"
tags = ["portfolio", "minimal", "clean", "responsive", "blog", "personal"]
features = ["responsive", "blog", "portfolio", "clean", "minimal", "LaTeX support"]
min_version = "0.41.0"

[author]
  name = "Dominik Ritzenhoff"
  homepage = "https://dominikritzenhoff.com"
