name = "ritzy"
license = "MIT"
licenselink = "https://github.com/ddritzenhoff/ritzy/blob/main/LICENSE"
description = "A bare-bones theme for bloggers"

homepage = "https://github.com/ddritzenhoff/ritzy"

demosite = "https://dominikritzenhoff.com"

tags = ["blog", "minimal", "clean", "personal"]
features = ["LaTeX support", "fast loading", "author profile"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.41.0"

[author]
  name = "Dominik Ritzenhoff"
  homepage = "https://dominikritzenhoff.com"
